### ISSUE TITLE
abfe_cli module inaccesible to the cli-abfe

### ISSUE THREAD

**Issue by Nithishwer** [bigginlab/ABFE_workflow#16]
After initializing the conda environment using the yml script, trying to access cli-abfe's help results in : 

Traceback (most recent call last):
  File "/biggin/b211/reub0138/mambaforge/envs/abfe/bin/cli-abfe", line 17, in <module>
    from abfe_cli.ABFECalculator import main
ModuleNotFoundError: No module named 'abfe_cli'

Clearly, the cli-abfe script located at ../../mambaforge/envs/abfe/bin/ did not find the file 'ABFECalculator' under the 'abfe_cli' folder. This is because the abfe_cli folder is in the repository directory 'ABFE_workflow'. Therefore I decided to add ABFE_workflow to the system path in the cli-abfe script with:

\# Add the ABFE github repo to the path
sys.path.append('/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main')

This workaround resolved the issue and the cli worked as expected. The alpha version might need a more refined solution.

**Comment by RiesBen** [comment]
Hi @Nithishwer,
first thanks for checking the code! :)

Sorry I need to ask one or two questions, that might seem obvious to you, as I could not reproduce the issue. ;) 

Did you after installing the conda env wit the `.yml`, execute `pip install . ` in the git repository, in order to install the ABFE package? (This should remove the need of sys.path.append)

**Comment by Nithishwer** [comment]
Hi @RiesBen 

I did a mamba install with `/yml `and used `pip install.` I'll try redoing it with the updated package to see if it is reproducible.

**Comment by Nithishwer** [comment]
I still seem to be getting this error:

    from abfe_cli.ABFECalculator import main
ModuleNotFoundError: No module named 'abfe_cli'

**Comment by RiesBen** [comment]
ok, could reproduce the problem now and I restructured file in a more pypi like way. 
for me now it works.  with: https://github.com/bigginlab/ABFE_workflow/commit/3e73990cb7033f5d869fb95c26b7bd84ce3ac417
