### ISSUE TITLE
-submit argument unrecognised

### ISSUE THREAD

**Issue by Nithishwer** [bigginlab/ABFE_workflow#20]
When I try to execute example_execution.sh with bash,

I get the following error:

usage: cli-abfe [-h] -p PROTEIN_PDB_PATH -l LIGAND_SDF_DIR -o OUTPUT_DIR_PATH [-c COFACTOR_SDF_PATH]
                [-pn PROJECT_NAME] [-nr NUMBER_OF_REPLICATES] [-njr NUMBER_OF_PARALLEL_RECEPTOR_JOBS]
                [-njl NUMBER_OF_PARALLEL_LIGAND_JOBS] [-ncl NUMBER_OF_CPUS_PER_LIGAND_JOB] [-sff SMALL_MOL_FF]
                [-nosubmit] [-nogpu] [-nohybrid]
cli-abfe: error: unrecognized arguments: -submit

Clearly because cli-abfe has -nosubmit as an argument changing the bash script to -nosubmit solved the issue

**Comment by RiesBen** [comment]
fixed.
