### ISSUE TITLE
Unexpected keyword argument 'nosubmit'

### ISSUE THREAD

**Issue by Nithishwer** [bigginlab/ABFE_workflow#21]
Trying to execute example_execution_gmx.sh gives the following error

usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'activate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'env')
False
Traceback (most recent call last):
  File "/biggin/b211/reub0138/mambaforge/envs/abfe2/bin/cli-abfe-gmx", line 10, in <module>
    sys.exit(main())
  File "/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/abfe_cli/ABFECalculatorGmx.py", line 50, in main
    res = calculate_abfe_gmx(input_dir=args.gmx_files_root_dir, out_root_folder_path=args.output_dir_path, approach_name=args.project_name,
TypeError: calculate_abfe_gmx() got an unexpected keyword argument 'nosubmit'

Might have to switch the variable

**Comment by RiesBen** [comment]
fixed with: 8b41415c7602e825a1822c09f9a85173ba3279e6
