### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by EricChen521** [bigginlab/ABFE_workflow#26]
Hi, I experienced an error related to Scipy using `mamba env create --file environment.yml`.
 Any idea why?

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scipy
ERROR: Could not build wheels for scipy, which is required to install pyproject.toml-based projects

failed
```

**Comment by RiesBen** [comment]
@EricChen521 hej Eric,
this looks weird! looking into it :)

**Comment by ErikZhang-9762** [comment]
Hi, I have the same problem.

The error should occur when installing MDRestraintsGenerator using pip

The problem can be reproduced using the following command
```
pip install MDRestraintsGenerator
```

and scipy version is 1.7.3
```
conda list | grep scipy
scipy                     1.7.3           py310hea5193d_0    conda-forge
```

Is there a solution to this problem now?

**Comment by RiesBen** [comment]
Hej, 
it took some time, till I had time to look into this. 

I updated the `environment.yml` and pinned the numpy version to 1.22, now at least the CI works. how does that look on your end? :)

**Comment by philbiggin** [comment]
OK - its a been a few months now so in the absence of information saying otherwise I think this is fixed.
