### ISSUE TITLE
Updating CyclophilinD TestSystem

### ISSUE THREAD

**Issue by RiesBen** [bigginlab/ABFE_workflow#6]
for the current workflow we need sdfs of the ligands with the correct bond-order information.

**Comment by ale94mleon** [comment]
I can not get the OpenFF parameters for those ligands becasue I can not construct the opneff  `Molecule` object:

```python
from rdkit import Chem
import glob
from openff.toolkit.topology import Molecule
sdfs = glob.glob('*.sdf')
import os
for sdf in sdfs:
    name = os.path.splitext(sdf)[0]
    mol = Chem.MolFromMolFile(sdf)
    # print(name, mol)
    try:
        offmol = Molecule(mol) # the same Molecule(sdf): UndefinedStereochemistryError
    except:
        print(name)
```

I am always getting the same Exception: `UndefinedStereochemistryError`. I founded the same problems here: [1](https://github.com/openforcefield/openff-toolkit/issues/412) and [2](https://github.com/openforcefield/openff-toolkit/issues/1410).

The other is that the ligands are not close to the protein, is this right? Should not they be pre-docked?
![Screenshot from 2023-03-29 17-36-16](https://user-images.githubusercontent.com/75276620/228591994-b4b358c9-5142-4d67-b0cd-6165401db8b8.png)

**Comment by RiesBen** [comment]
Oha! That sounds like the hydrogens are not correctly added. however structures look good :)

**Comment by RiesBen** [comment]
@ale94mleon I updated the ligand files, now you should not get an error anymore! :)

**Comment by ale94mleon** [comment]
Thanks. Now the new ligands are in the binding site and I can get their parameters. I modify the binding part in order to put it at snakemake level. I want to try on the cluster, if everything goes well, should I request a PR?

**Comment by RiesBen** [comment]
did this all work for you?
